version: "3.9"
name: pdfwebsigner
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
